name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: I expected X, but Y happened.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a model...
        2. Apply FilterApplicator...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Details about your environment.
      value: |
        - PHP Version:
        - Laravel Version:
        - core-foundation Version:
    validations:
      required: true
