name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you want to achieve.
      placeholder: I would like to see a feature that...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
